### ISSUE TITLE
Feature request : ability to drag the widget

### ISSUE THREAD

**Issue by ChameleonScales** [wavexx/screenkey#69] opened 2018-05-04 19:47 UTC
When you make a video turorial or espacially when you teach a program live in front of people, you encounter situations where some important information is hidden behind the screenkey widget, no matter how clever its placement was. Another situation is when you want to draw attention to a particular area of the screen for a while but don't want your viewers to lose sight of the keys and mouse, so you'd like to bring the widget closer to that area.
In these situations, having the ability to drag the widget with the mouse (in the best case by using the default modifier key that you use to drag any other window in your linux distro) would solve this problem.
Keymon does this, although iirc it doesn't require a modifier key, which I think is prone to accidentally dragging it.

**Comment by wavexx** [comment] 2018-05-06 15:02
Early this year I experimented a bit by moving the field up/down according to the mouse position (by always moving to the opposite side), and it's not too bad. But it doesn't work if you're not using the mouse, of course.

Dragging seem sensible to me, although I suspect it would get in the way very often. The original screenkey had an opaque window (that you could drag regularly using your window manager, usually with super+drag). It gets tiring, quickly :/

**Comment by ChameleonScales** [comment] 2018-05-06 23:03
I've had keymon users say they like screenkey's design but they still use keymon because you can drag the widget.
I don't think it's so sensible if you have to use super+LMB (or whatever modifier key you've set up in your window manager).
At least it would be cool if when you fit the widget in a selected window that it moved with the window, which is not the case currently.

**Comment by wavexx** [comment] 2018-05-06 23:27
On Mon, May 07 2018, Caetano Veyssières wrote:
>I've had keymon users say they like screenkey's design but they still
> use keymon because you can drag the widget.

I also still use keymon for some features :/

> At least it would be cool if you fit the widget in a selected window
> that it moved with the window which is not the case currently.

This is something I'd like to do independently: tracking an existing
window position.

If you currently select a window, and move it, the position of the text
doesn't change, but it really _should_.

So if choose "fixed" and select an existing window it *would* do that.
But err... a bit ugly in my mind.

The problem is that screenkey hides the window, which makes dragging
hard without adding some extra hotkey.

**Comment by ChameleonScales** [comment] 2018-05-07 00:12
If this "follow window" feature was added, it would also somewhat solve the other dragging issue, as you could add a transparent GTK window, fit screenkey into it and drag that window instead.

**Comment by wavexx** [comment] 2018-05-07 12:39
I added #72 for the base requirement

**Closed as completed** 2019-01-29 16:18 UTC
